name: Android CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-35
            build-tools;35.0.0

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build and test
        uses: gradle/gradle-build-action@v3
        with:
          arguments: |
            clean
            assembleDebug
            test
            lint

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            **/build/reports/tests/**/*
            **/build/reports/lint-results.html
